name: on-push
on: push

permissions:
  contents: read

jobs:
  lint-check:
    name: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  test:
    runs-on: ubuntu-latest
    needs: lint-check

    steps:
      - uses: actions/checkout@v4
      - run: make test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - run: make build